version: '3.8'

services:
  php-myges-calendar:
    image: myges-calendar:latest
    ports:
      - "0.0.0.0:40000:80"
    volumes:
      - <path to website directory>:/var/www/html
    container_name: myges-calendar
    restart: unless-stopped
  
  python-myges-calendar:
    image: myges-calendar-python:latest
    container_name: myges-calendar-python
    ports:
      - "0.0.0.0:40500:40500"
    volumes:
      - <path to api-python directory>:/app
    restart: unless-stopped
